name: Canary Release
on:
  push:
    branches:
      - next

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GEINS_API_KEY: ${{ secrets.GEINS_API_KEY }}
      GEINS_ACCOUNT_NAME: ${{ secrets.GEINS_ACCOUNT_NAME }}
      GEINS_CHANNEL: ${{ secrets.GEINS_CHANNEL }}
      GEINS_TLD: ${{ secrets.GEINS_TLD }}
      GEINS_LOCALE: ${{ secrets.GEINS_LOCALE }}
      GEINS_MARKET: ${{ secrets.GEINS_MARKET }}
      GEINS_ENVIRONMENT: ${{ secrets.GEINS_ENVIRONMENT }}
      GEINS_USERNAME: ${{ secrets.GEINS_USERNAME }}
      GEINS_PASSWORD: ${{ secrets.GEINS_PASSWORD }}
      GEINS_CMS_FAMILY: ${{ secrets.GEINS_CMS_FAMILY }}
      GEINS_CMS_AREA: ${{ secrets.GEINS_CMS_AREA }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --immutable

      - name: Build Packages
        run: yarn build:sdk

      - name: Run Tests
        run: yarn test

      - name: Release snapshot
        run: |
          yarn changeset version --snapshot canary --no-git-tag
          yarn changeset publish --tag canary --no-git-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
